### PR TITLE
feature/add-owner-organization-id

### LINKED ISSUE #57: Users and organizations
Problem description: 

In most systems, including NODES, users can be members of more than one organization. Orders, trades, portfolios etc are connected to organizations. However, in UMEI we don't have organization ids anywhere. This led e.g. creating an Order to be somewhat tricky to implement. 

Current solution in NODES: 

In my UMEI server implementation, I have solved this by adding two features: 
- an endpoint (/me) showing information about the current logged in user (based on authentication token), and which organizations and roles this user has access to
- adding a header, "ActingOrganizationId", two all request. This header is used when e.g. creating an order, so that the order is assigned to the correct organization. 
- When retrieving orders, portfolios etc, this information can not be mapped to UMEI data models so this information is currently unavailable. 

Question: 

Should we add the string-property "OwnerOrganizationId" to Order, Trade and Portfolio? Or standardize the header approach? Or leave it outside the scope of the UMEI specification?

### PR DESCRIPTION
**Pull request by narve**
Fixes #57

### CODE REVIEW

**Comment by cdmNSIDE** [comment]
Wouldn't it be useful to add this OwnerOrganisationId to the Baselines, MeterReadings and FlexibilityZones ? 

Do you think it would be useful to explain in the glossary what is the distinction between a user and an organization? Or is it self-explanatory ?

**Comment by narve** [comment]
FlexibilityZones: Yes, probably, good point. 
Baselines and meter readings: Possibly. They are already connected to portfolios, which have an owner, so I don't see the need, but if N-Sides want that field I don't mind. 

In NODES, that field will probably be validated but ignored when creating, and calculated when fetched.

**Comment by cdmNSIDE** [comment]
I do not understand your comment, because Orders and Trades are also connected to portfolios..

**Comment by narve** [comment]
Orders and Trades are not necessarily connected to portfolios. 

Buy-orders, typically, do not reference portfolios, only sell-orders. And ditto with trades - usually only sell-trades are connected to a portfolio.

**Review by cdmNSIDE — DISMISSED** [review]

**Comment by narve** [comment]
Right, then I will merge it :)

**Comment by narve** [comment]
after solving the merge conflicts, so not today :(

**Pull request merged**
