### PR TITLE
Move timestamp from parameters to schemas

### PR DESCRIPTION
**Pull request by narve**

### CODE REVIEW

**Comment by narve** [comment]
Hopefully this PR can be used instead of https://github.com/euniversal/umei-api-specification/pull/61

**Comment by pruN-SIDE** [comment]
Indeed, moving to schema is way better than the repetition, I'll prefer using this as well

**Comment by narve** [comment]
> Indeed, moving to schema is way better than the repetition, I'll prefer using this as well. I'll close pull request #61 if that's ok

Yes, please do, but verify first that this PR resolves your code generation issue.

**Comment by pruN-SIDE** [comment]
@narve I did, and it works fine, thank you again

**Comment by narve** [comment]
Excellent, feel free to merge this and close the other one :)

**Review by pruN-SIDE — APPROVED** [review]

**Pull request merged**
