### PR TITLE
Add reference to longflex contract

### PR DESCRIPTION
**Pull request by narve**

### CODE REVIEW

**Comment by ArnaudDebray** [comment]
Hello Narve,

I understand the idea behind your proposal but we imagined this in a slightly different way. 
In our vision, a market platform already knows which LT contract were accepted in the past for each portfolio and each time period. We then prefer to link automatically on the platform side based on the portfolio and the timestamp. (i.e. if there was an accepted LT offer of portfolio X for period Y, then, when that portfolio X will submit a ST offer for period Y it will be automatically linked)

Is there a reason to prefer asking the user to explicitly put this link in the request? What happens if he forgets?

**Comment by OysteinDE** [comment]
> Hello Narve,
> 
> I understand the idea behind your proposal but we imagined this in a slightly different way. In our vision, a market platform already knows which LT contract were accepted in the past for each portfolio and each time period. We then prefer to link automatically on the platform side based on the portfolio and the timestamp. (i.e. if there was an accepted LT offer of portfolio X for period Y, then, when that portfolio X will submit a ST offer for period Y it will be automatically linked)
> 
> Is there a reason to prefer asking the user to explicitly put this link in the request? What happens if he forgets?

Hi,

Your vision is a probable solution. 
However, in some of our current projects, we do have customers (FSPs) that have made several LongFlex availability contracts with the same Portfolio. In order for us to do settlement, we need to know which contract a specific order is linked to, which is why we use LongFlexContractId on ShortFlex orders.

**Comment by narve** [comment]
Building further on @OysteinDE comment: So, in our case, the buyer would need to provide longflexContractId for us to link it. 
Furthermore, an FSP is free to provide shortflex orders that are outside any contracts. 
I suggest that it is up each FMO whether they: 
- require longflexContractId in order to link orders to longflex contracts (NODES)
- automatically link orders to longflex contracts (N-Side)
- a combination (link if single contract)

**Comment by ArnaudDebray** [comment]
ok for us :)

**Review by ArnaudDebray — APPROVED** [review]

**Pull request merged**
