### PR TITLE
Add the grid node id in the asset portfolio

### PR DESCRIPTION
**Pull request by cdmNSIDE**
And remove the grid node id in the orders since it can be retrieved from the asset portfolio

### CODE REVIEW

**Comment by narve** [comment]
Hm this needs to be discussed. While a portfolio in general might have a grid node id, it is not obvious that it will always offer flexibility on that particular grid node. I don't see any particular use case for that now, but I will discuss it internally. 

However, removing grid node id from orders does not make sense to us. If you post a BUY order you don't specify a portfolio, but you still want to declare where in the grid you want flexibility?

**Comment by cdmNSIDE** [comment]
Oh indeed, I forgot this particularity of the buy orders. I agree to keep the gridNodeId in the orders then. And in that case, there is no point to add it in the portfolio..

**Comment by cdmNSIDE** [comment]
If we do not add the gridNodeId in the portfolios, then I guess we may have to add a gridNodeId (or replace the assetPortfolioId by gridNodeId) in the baselines and in the measurements. What do you think ?

**Comment by narve** [comment]
We can not replace the portfolio id in a baseline with a grid node. The baselines applies to a specific asset(portfolio). There typically are many portfolios (and thus baselines) per grid node.

**Comment by narve** [comment]
Furthermore, the FSPs are not necessarily aware which grid node id the portfolio is placed on, that is the responsibility of the DSO.

**Comment by narve** [comment]
And in addition, we have a use case where we have movable assets, i.e. assets which can swap location (and thus grid node). The baselines would in that case better be linked to a portfolio, removing the need to update the grid node for already saved baselines. 

However, we don't see a problem with adding grid node id to BaselineInterval per se. However, it should be up to the FMO whether this field is forbidden, optional or required.

**Review by narve — CHANGES_REQUESTED** [review]
See comment in PR

**Comment by ArnaudDebray** [comment]
Hello Narve, 
I think there is a misunderstanding/misalignment on the workflow here. In our understanding, the asset portfolios are defined by the FSP/aggregator and should be related to a gridNode.

We should spend time during the meeting today to clarify the process. Then after good alignment on the process, we can discuss the impacts on the API.

Concerning the movable assets, can you clarify the use case ? From my business point of view, I see a lot of potential problems when doing this. And I really don't believe this has ever been considered in any of the demos.

**Comment by narve** [comment]
Note from meeting: Clean up the PR so that it only adds gridNodeId to Portfolio and nothing else.

**Review by narve — APPROVED** [review]

**Review by narve — APPROVED** [review]

**Review by ArnaudDebray — APPROVED** [review]

**Pull request merged**
