### PR TITLE
removed timestamp parameter

### PR DESCRIPTION
**Pull request by pruN-SIDE**
Remove the timestamp parameter used to define the to and from periods (using one parameter to generate another one was generating errors for the api generation).

Note: this PR also contains the changes done by @cdmNSIDE for the flexibilityZones and has to be merged after her PR.

### CODE REVIEW

**Comment by cdmNSIDE** [comment]
Hello @pruN-SIDE :)
Can you change the destination of this PR (use the branch with the flexibility zones instead of "main") ? It will be much easier for us to do the review. Thanks

**Comment by narve** [comment]
I would suggest another approach. This way we have lots of duplications in the file. 

As far as I can see, the problem was that the timeStamp-definition was put in the parameters section but it should have been in the schemas-section.

**Comment by narve** [comment]
Can you have a look at my PR and see if that solves the problem? Or otherwise detail the problems so we can find a better solution?

**Comment by pruN-SIDE** [comment]
Not needed since timeStamp was moved to Schemas

**Pull request closed without merging**
