### PR TITLE
rename trade id

### PR DESCRIPTION
**Pull request by cdmNSIDE**

### CODE REVIEW

**Review by ArnaudDebray — APPROVED** [review]

**Comment by narve** [comment]
I suggest that we are consistent. Currently, each data type (trade, order, etc) has a property "id" which refers to the object itself. In this way, we can model this using a supertype / interface in data types.

**Review by narve — CHANGES_REQUESTED** [review]
Suggest dropping this to be consistent across all data types

**Comment by cdmNSIDE** [comment]
Hello @narve ,

> Currently, each data type (trade, order, etc) has a property "id" which refers to the object itself. 

Well not, the id of the order is written "OrderId", the one of the baseline is called "BaselineId" and so on.
May be it's something that has been changed in another PR, I don't remember what was the initial version

**Comment by narve** [comment]
> Hello @narve ,
> 
> > Currently, each data type (trade, order, etc) has a property "id" which refers to the object itself.
> 
> Well not, the id of the order is written "OrderId", the one of the baseline is called "BaselineId" and so on. May be it's something that has been changed in another PR, I don't remember what was the initial version

Yes, you are correct. I don't know when that happened. I am in favor of using "id" as the name of the "primary key" on all data types, to be consistent. What do N-Side think?

**Comment by narve** [comment]
Mostly this is to enable a common super type (super-class, interface) for all classes in generated code.

**Comment by cdmNSIDE** [comment]
Ok I have pushed a new commit with the modification suggested

**Review by ArnaudDebray — APPROVED** [review]

**Review by narve — APPROVED** [review]

**Pull request merged**
