### PR TITLE
Remove the request to retrieve the grid hierarchy

### PR DESCRIPTION
**Pull request by cdmNSIDE**

### CODE REVIEW

**Review by narve — COMMENTED** [review]
I agree that the current method may require some changes. However, I think there should be a least one standardized way of retrieving the grid structure. Do you have an alternative API / proposal?

**Comment by cdmNSIDE** [comment]
Hello Narve,
Could you please remind me why there is a need to retrieve the grid hierarchy ? 
Who needs to access that information?
Is there a direct application in the demos of EUniversal ?

**Comment by narve** [comment]
Well, yes, certainly the market participants (especially buyers/DSOs) need to retrieve the grid hierarchy. They will put the buy orders in a certain place in the grid, thus they need to know the id/reference to that place in the grid. 

Knowing these IDs are a hard requirement for most participants. The only question is if this should be part of the UEMI standard or not. If not, they will have to retrieve these IDs in a different way, using non-UEMI APIs.

**Comment by ArnaudDebray** [comment]
as PR#12, this is related to the process => to be discussed in meeting.
I understand the use in general. But in the framework of the demos, I'm not sure it's mandatory

**Comment by cdmNSIDE** [comment]
Agreement during the meeting of 10/11/2021 to remove the grid hierarchy from the UMEI

**Review by narve — DISMISSED** [review]

**Comment by narve** [comment]
@cdmNSIDE can you update this PR so we can merge it?

**Review by ArnaudDebray — APPROVED** [review]

**Review by ArnaudDebray — APPROVED** [review]

**Review by narve — APPROVED** [review]

**Pull request merged**
