### PR TITLE
Add optional fields in the orders to model other type of products

### PR DESCRIPTION
**Pull request by cdmNSIDE**
Hello @narve ,
We need other types of orders for the Portuguese demo.
I have added optional fields in the API to model the new characteristics of those orders.

### CODE REVIEW

**Comment by narve** [comment]
See main discussion in issue: #23

**Comment by cdmNSIDE** [comment]
the fields are defined as "nullable:true", so it should be ok, no ?

**Comment by narve** [comment]
After discussion: Some modifications are needed, both in data definitions and descriptions.

**Comment by cdmNSIDE** [comment]
@narve I pushed a few changes. You can still propose new names for the different types of orders if you want

**Review by cdmNSIDE — COMMENTED** [review]
OK to use lower cases for the id, but then use it everywhere

**Comment by cdmNSIDE** [comment]
@narve I am ok with your last changes but I can not approve this PR by myself

**Review by ArnaudDebray — DISMISSED** [review]

**Review by narve — APPROVED** [review]

**Comment by narve** [comment]
Ok to merge now, @cdmNSIDE ?

**Review by ArnaudDebray — APPROVED** [review]

**Pull request merged**
