### PR TITLE
Replace "periodFrom" and "periodTo" by "startTime" and "duration"

### PR DESCRIPTION
**Pull request by cdmNSIDE**

### CODE REVIEW

**Comment by narve** [comment]
I don't really see the point of this PR. I understand that you use startTime and duration, but are there any particular reasons for preferring startTime and duration to periodFrom and periodTo? I believe those names are quite clear and unambiguous. 

If we were to consider this change, we at least would have to clarify what  "duration" means?

**Review by narve — COMMENTED** [review]
See comments in PR

**Comment by narve** [comment]
Well, I don't see any significant difference. We would still have to check that duration is positive (equivalent to periodTo being after periodFrom), and that the startTime/periodTo is allowed (e.g. the order does not start at 13:03), in addition to checking the granularity against the market rules. Some participants (TSOs) can override the market time granularity rules anyway. 

Furthermore, in our case we support block orders, each block having a duration. This means that we can post an order for e.g. 2 blocks, of 15 minutes each, in the period between 13:00 and 14:00. In that regard "duration" would be ambigous - there is one "blockDuration" and one "orderDuration".  

So, if this is really important to you, it is ok for us. But then I want the field to be "durationInSeconds" at least, because supporting short orders (30s) can be allowed in some markets.

**Comment by cdmNSIDE** [comment]
After internal discussion we agree to keep the "periodTo" and "periodFrom"

**Review by ArnaudDebray — APPROVED** [review]

**Comment by ArnaudDebray** [comment]
last validation was a mistake from me. I wanted to reject following your comment. @cdmNSIDE can you drop the PR ?

**Pull request closed without merging**
